"""initial migration

Revision ID: 5abebab09443
Revises: 
Create Date: 2026-04-24 01:16:46.251201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abebab09443'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('arc_overview', sa.Text(), nullable=True),
    sa.Column('style_guide', sa.Text(), nullable=True),
    sa.Column('world_bible_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'archived', name='storystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('characters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality_json', sa.JSON(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_characters_story', 'characters', ['story_id'], unique=False)
    op.create_table('story_outlines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('outline_date', sa.String(length=10), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outline_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'used', 'skipped', name='outlinestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outlines_status', 'story_outlines', ['status'], unique=False)
    op.create_index('ix_outlines_story_date', 'story_outlines', ['story_id', 'outline_date'], unique=False)
    op.create_table('story_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('current_chapter_no', sa.Integer(), nullable=False),
    sa.Column('current_arc', sa.String(length=255), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('current_conflict', sa.Text(), nullable=True),
    sa.Column('world_state_json', sa.JSON(), nullable=True),
    sa.Column('active_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('outline_id', sa.BigInteger(), nullable=True),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(length=4294967295), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'approved', 'rewriting', name='chapterstatus'), nullable=False),
    sa.Column('review_score', sa.SmallInteger(), nullable=True),
    sa.Column('needs_rewrite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['story_outlines.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapters_status', 'chapters', ['status'], unique=False)
    op.create_index('ix_chapters_story_no', 'chapters', ['story_id', 'chapter_no'], unique=False)
    op.create_table('character_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('realm', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('inventory_json', sa.JSON(), nullable=True),
    sa.Column('secrets_known_json', sa.JSON(), nullable=True),
    sa.Column('state_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charstate_chapter_no', 'character_states', ['chapter_no'], unique=False)
    op.create_index('ix_charstate_story_char', 'character_states', ['story_id', 'character_id'], unique=False)
    op.create_table('story_hooks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_no_created', sa.Integer(), nullable=False),
    sa.Column('hook_text', sa.Text(), nullable=False),
    sa.Column('related_character_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='hookstatus'), nullable=False),
    sa.Column('resolved_in_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hooks_story_status', 'story_hooks', ['story_id', 'status'], unique=False)
    op.create_table('chapter_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('verdict', sa.String(length=64), nullable=False),
    sa.Column('strengths_json', sa.JSON(), nullable=True),
    sa.Column('weaknesses_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rewrite_notes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_chapter', 'chapter_reviews', ['chapter_id'], unique=False)
    op.create_table('chapter_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_events_json', sa.JSON(), nullable=True),
    sa.Column('character_updates_json', sa.JSON(), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('foreshadow_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_index('ix_csummary_story_no', 'chapter_summaries', ['story_id', 'chapter_no'], unique=False)
    op.create_table('story_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('characters_involved_json', sa.JSON(), nullable=True),
    sa.Column('impact_level', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_story_no', 'story_events', ['story_id', 'chapter_no'], unique=False)
    op.create_index('ix_events_type', 'story_events', ['event_type'], unique=False)
    op.create_table('story_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('outline_id', sa.BigInteger(), nullable=True),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.Enum('plan', 'write', 'review', 'rewrite', 'memory_update', name='tasktype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['outline_id'], ['story_outlines.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_scheduled', 'story_tasks', ['scheduled_for'], unique=False)
    op.create_index('ix_tasks_story_status', 'story_tasks', ['story_id', 'status'], unique=False)
    op.create_index('ix_tasks_type_status', 'story_tasks', ['task_type', 'status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('story_id', sa.BigInteger(), nullable=True),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('started', 'done', 'failed', name='agentrunstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['story_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_agent_status', 'agent_runs', ['agent_name', 'status'], unique=False)
    op.create_index('ix_runs_story', 'agent_runs', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runs_story', table_name='agent_runs')
    op.drop_index('ix_runs_agent_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_tasks_type_status', table_name='story_tasks')
    op.drop_index('ix_tasks_story_status', table_name='story_tasks')
    op.drop_index('ix_tasks_scheduled', table_name='story_tasks')
    op.drop_table('story_tasks')
    op.drop_index('ix_events_type', table_name='story_events')
    op.drop_index('ix_events_story_no', table_name='story_events')
    op.drop_table('story_events')
    op.drop_index('ix_csummary_story_no', table_name='chapter_summaries')
    op.drop_table('chapter_summaries')
    op.drop_index('ix_review_chapter', table_name='chapter_reviews')
    op.drop_table('chapter_reviews')
    op.drop_index('ix_hooks_story_status', table_name='story_hooks')
    op.drop_table('story_hooks')
    op.drop_index('ix_charstate_story_char', table_name='character_states')
    op.drop_index('ix_charstate_chapter_no', table_name='character_states')
    op.drop_table('character_states')
    op.drop_index('ix_chapters_story_no', table_name='chapters')
    op.drop_index('ix_chapters_status', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('story_states')
    op.drop_index('ix_outlines_story_date', table_name='story_outlines')
    op.drop_index('ix_outlines_status', table_name='story_outlines')
    op.drop_table('story_outlines')
    op.drop_index('ix_characters_story', table_name='characters')
    op.drop_table('characters')
    op.drop_table('stories')
    # ### end Alembic commands ###
